<div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">Utilities</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="card">
            <label for="">for testing purposes only</label>
            2049Z-1BSTT-T0KOIZ <br>
            TS88_S <br>
            LT3999 <br>
            LT3999EDD#PBF-T0 <br>
            LTC3608EWKG#PBF-T0 <br>
            AD5301BRJCU-T1Z
        </div>
    </div>
</div>